### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by weijia-cheng** [chapkachapka/j-sheridan-le-fanu_the-wyvern-mystery#1]
# Typography

- [x] `chapter-26`: The hyphen in `Oh! ve-ry` should be a non-break hyphen.

# Spelling

- [x] `chapter-50`: `re infectâ` should be modernized to `re infecta`.
- [x] `chapter-40`: I think the `tho˚` -> `though` modernization can be reverted since it is in a vernacular context.

# Semantics

- [x] `chapter-28`: Should “Vrau’s” be emphasized here, even though it is not elsewhere? This seems like it might have been done since it was being treated as a non-English word.
- [x] `chapter-63`: I think the latter part of `Tag-rag-merry-derry-perrywig and hatband-hic-hoc-horum-genetivo` can be marked as Latin.
- [x] `grep --recursive --line-number "<i>" src/epub/text/*.xhtml` indicates some italics that still need semantics.

# Metadata

- [x] Run `se clean` to fix whitespace issues.

# CSS

- [x] I think this will work better for your envelope blockquote in chapter-14:

```
#chapter-14 blockquote p{
	text-indent: 0;
}

#chapter-14 blockquote p:nth-of-type(2){
	text-indent: 3em;
}

#chapter-14 blockquote p:nth-of-type(3){
	text-indent: 6em;
}

#chapter-14 blockquote p:nth-of-type(4){
	text-indent: 9em;
}
```

# Meta

- [x] cff6600ebbe5bc44a7a2a0532e4b3b43a39a5408: Needs to be marked as editorial.

**Comment by chapkachapka** [comment]
These should all be taken care of, thanks!

**Comment by weijia-cheng** [comment]
The changes themselves look good, however when you updated the editorial commit message, it seems you merged the changes instead of force-pushing them. As a result you duplicated your commit history here instead of rewriting the editorial message. Since this can be somewhat complicated issue to resolve, I dropped all of the duplicated commits by interactive rebasing from d866465724a210fbafa5da35a7d00648abc4b5d8 and pushed the cleaned history to my own version of the repository: https://github.com/weijia-cheng/j-sheridan-le-fanu_the-wyvern-mystery
